version: "1.3"
services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend_c
  #   ports:
  #     - '3000:3000'
  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=SLIDO_LITE
      - POSTGRES_USER=asfand
      - POSTGRES_PASSWORD=asfand247
    ports:
        - 5432:5432

  # backend:
  #   build: ./backend
  #   container_name: backend_c
  #   ports:
  #     - 8080:8080

  